create database codelyser;
drop database codelyser;
show tables;
use codelyser;
select * from template;
select * from testcase;
select * from question;
select * from candidate;
select * from candidate_question;
delete from question where id=203;
drop table candidate;